# @package _global_
# VHH (nanobody) run configuration for IL3

# General run settings
type: "nb"
cdr_lengths: [11, 8, 18]
fw_lengths: [25,17,38,14]
pregenerate_seeds: false
vh_first: null # not needed for nanobodies
vh_len: null # not needed for nanobodies  
vl_len: null # not needed for nanobodies

# Loss function parameters
weights_plddt: 1.0
weights_i_plddt: 1.0
weights_pae_intra: 0.1
weights_pae_inter: 0.3
weights_iptm: 0.7
weights_con_intra: 0.1
weights_con_inter: 0.2
weights_rg: 0.1
weights_helix: 0.1
weights_beta: 0.1

intra_contact_distance: 14.0
inter_contact_distance: 20.0
intra_contact_number: 2
inter_contact_number: 10
framework_contact_loss: true
framework_contact_offset: 0.5

# Hallucination settings
logits_steps: 60
softmax_steps: 35
search_steps: 10
search_mutation_rate: 0.05
plddt_threshold: 0.75
i_ptm_threshold: 0.68
i_pae_threshold: 0.30
seq_entropy_threshold: 0.10

# IgLM settings
grad_merge_method: "pcgrad"
iglm_scale: [0.0, 0.2, 0.4, 1.0]
iglm_temp: 0.6
iglm_species: "[HUMAN]"
seq_init_mode: ["gumbel", "soft"]  # STATIC: Fixed list, no argparse option
bias_redesign: 10
use_pos_distance: true
clear_best: true

# Sequence redesign settings
mpnn_fix_interface: true
num_seqs: 40
max_mpnn_sequences: 5
sampling_temp: 0.1
backbone_noise: 0.0
model_path: "abmpnn"
mpnn_weights: "abmpnn"

# Structure prediction settings
structure_model: "af3"
msa_mode: "target"

# AF3 configuration (required when structure_model == "af3")
af3_repo_path: null
af3_sif_path: null
af3_model_dir: null
af3_db_dir: null
msa_db_dir: null
use_metagenomic_db: false

# Template removal settings
rm_template_seq: true
rm_template_sc: false
rm_binder: false
rm_binder_seq: true
rm_binder_sc: true

###### REMAINING SETTINGS ######
# These settings are typically not changed from run to run.

# Model and Optimization settings
learning_rate: 0.1
optimizer: "sgd"
normalize_gradient: true
linear_lr_annealing: true
min_lr_scale: 0.25
use_multimer_design: true
sample_models: true
num_models: 1
num_recycles_design: 3
recycle_mode: "last"

# Other loss settings
use_helix_loss: true
use_beta_loss: true
beta_loss_type: "strand"
use_rg_loss: true
use_termini_distance_loss: false
use_i_ptm_loss: true

# File management settings
save_design_animations: false
save_design_trajectory_plots: false

# Other settings
omit_AAs: false
force_reject_AA: false
dgram_cce: 0.01
show_config: true

# Filter thresholds (moved from hardcoded values in code)
clash_threshold: 2.4           # Å for atomic clash detection
hotspot_distance_threshold: 5.3  # Å to consider residues near hotspots
residue_contact_distance: 6.0    # Å threshold for residue-residue contact
min_cdr_hotspot_contacts: 3      # minimum hotspot contacts in CDRs
sap_limit_sasa: 3.0              # minimal SASA in patch to consider
sap_patch_radius: 7.5            # Å radius for SAP patch
sap_avg_sasa_patch_thr: 1.5      # average SASA threshold per patch
atom_distance_cutoff: 3.0        # Å threshold for atom distance in redesign