# @package filter.final
# Final filters for scFv PDL1
# These are more stringent filters applied at the end of the pipeline

# Structure metrics
clashes:
  value: 1
  operator: '<'

sc_rmsd:
  value: 7.0
  operator: '<'

binder_near_hotspot:
  value: true
  operator: '=='

cdr3_hotspot_contacts:
  value: 0
  operator: '>'

percent_interface_cdr:
  value: 0.7
  operator: '>'

interface_shape_comp:
  value: 0.5
  operator: '>'

interface_hbonds:
  value: 6
  operator: '>='

# Hydrophobicity metrics
surface_hydrophobicity:
  value: 0.42
  operator: '<'

interface_hydrophobicity:
  value: 45
  operator: '>'

# Confidence metrics
pdockq2:
  value: 0.23
  operator: '>'

external_plddt:
  value: 0.85
  operator: '>'

external_iptm:
  value: 0.74
  operator: '>'

external_ptm:
  value: 0.84
  operator: '>='

external_pae:
  value: 8
  operator: '<'